module Phlex
  module HTML
    module StandardElements
      def a: (**attributes) -> void
      def abbr: (**attributes) -> void
      def address: (**attributes) -> void
      def article: (**attributes) -> void
      def aside: (**attributes) -> void
      def b: (**attributes) -> void
      def bdi: (**attributes) -> void
      def bdo: (**attributes) -> void
      def blockquote: (**attributes) -> void
      def body: (**attributes) -> void
      def button: (**attributes) -> void
      def caption: (**attributes) -> void
      def cite: (**attributes) -> void
      def code: (**attributes) -> void
      def colgroup: (**attributes) -> void
      def data: (**attributes) -> void
      def datalist: (**attributes) -> void
      def dd: (**attributes) -> void
      def del: (**attributes) -> void
      def details: (**attributes) -> void
      def dfn: (**attributes) -> void
      def dialog: (**attributes) -> void
      def div: (**attributes) -> void
      def dl: (**attributes) -> void
      def dt: (**attributes) -> void
      def em: (**attributes) -> void
      def fieldset: (**attributes) -> void
      def figcaption: (**attributes) -> void
      def figure: (**attributes) -> void
      def footer: (**attributes) -> void
      def form: (**attributes) -> void
      def g: (**attributes) -> void
      def h1: (**attributes) -> void
      def h2: (**attributes) -> void
      def h3: (**attributes) -> void
      def h4: (**attributes) -> void
      def h5: (**attributes) -> void
      def h6: (**attributes) -> void
      def head: (**attributes) -> void
      def header: (**attributes) -> void
      def hgroup: (**attributes) -> void
      def html: (**attributes) -> void
      def i: (**attributes) -> void
      def iframe: (**attributes) -> void
      def ins: (**attributes) -> void
      def kbd: (**attributes) -> void
      def label: (**attributes) -> void
      def legend: (**attributes) -> void
      def li: (**attributes) -> void
      def main: (**attributes) -> void
      def map: (**attributes) -> void
      def mark: (**attributes) -> void
      def menuitem: (**attributes) -> void
      def meter: (**attributes) -> void
      def nav: (**attributes) -> void
      def noscript: (**attributes) -> void
      def object: (**attributes) -> void
      def ol: (**attributes) -> void
      def optgroup: (**attributes) -> void
      def option: (**attributes) -> void
      def output: (**attributes) -> void
      def p: (**attributes) -> void
      def path: (**attributes) -> void
      def picture: (**attributes) -> void
      def pre: (**attributes) -> void
      def progress: (**attributes) -> void
      def q: (**attributes) -> void
      def rp: (**attributes) -> void
      def rt: (**attributes) -> void
      def ruby: (**attributes) -> void
      def s: (**attributes) -> void
      def samp: (**attributes) -> void
      def script: (**attributes) -> void
      def section: (**attributes) -> void
      def select: (**attributes) -> void
      def slot: (**attributes) -> void
      def small: (**attributes) -> void
      def span: (**attributes) -> void
      def strong: (**attributes) -> void
      def style: (**attributes) -> void
      def sub: (**attributes) -> void
      def summary: (**attributes) -> void
      def sup: (**attributes) -> void
      def svg: (**attributes) -> void
      def table: (**attributes) -> void
      def tbody: (**attributes) -> void
      def td: (**attributes) -> void
      def template_tag: (**attributes) -> void
      def textarea: (**attributes) -> void
      def tfoot: (**attributes) -> void
      def th: (**attributes) -> void
      def thead: (**attributes) -> void
      def time: (**attributes) -> void
      def title: (**attributes) -> void
      def tr: (**attributes) -> void
      def u: (**attributes) -> void
      def ul: (**attributes) -> void
      def video: (**attributes) -> void
      def wbr: (**attributes) -> void
    end
  end
end
