inherit_from:
  - "https://www.goodcop.style/rubocop.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 2.7

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false



Security/Eval:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: false
