AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/CommentIndentation:
  AllowForAlignment: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/EmptyClass:
  AllowComments: true

Lint/MissingSuper:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/MethodParameterName:
  MinNameLength: 1

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BeginBlock:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/EndBlock:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfUnlessModifierOfIfUnless:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineMemoization:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/Send:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
