require:
  - ruby-next/rubocop

inherit_from:
  - "https://www.goodcop.style/rubocop.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: next

AllCops:
  Exclude:
    - 'lib/.rbnext/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false
