inherit_from:
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 3.2

# We need to disable this cop because it’s not compatible with TruffleRuby 23.1, which still needs a `require "set"`
Lint/RedundantRequireStatement:
  Enabled: false
