inherit_from:
  - "https://www.goodcop.style/rubocop.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 2.7

Style/ExplicitBlockArgument:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RedundantDoubleSplatHashBraces:
  Enabled: false

Style/OptionalArguments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false
