# frozen_string_literal: true

module Phlex::SVG::StandardElements
	extend Phlex::Elements

	REGISTERED_ELEMENTS = Concurrent::Map.new

	register_element :a, tag: "a"
	register_element :animate, tag: "animate"
	register_element :animateMotion, tag: "animateMotion"
	register_element :animateTransform, tag: "animateTransform"
	register_element :circle, tag: "circle"
	register_element :clipPath, tag: "clipPath"
	register_element :defs, tag: "defs"
	register_element :desc, tag: "desc"
	register_element :discard, tag: "discard"
	register_element :ellipse, tag: "ellipse"
	register_element :feBlend, tag: "feBlend"
	register_element :feColorMatrix, tag: "feColorMatrix"
	register_element :feComponentTransfer, tag: "feComponentTransfer"
	register_element :feComposite, tag: "feComposite"
	register_element :feConvolveMatrix, tag: "feConvolveMatrix"
	register_element :feDiffuseLighting, tag: "feDiffuseLighting"
	register_element :feDisplacementMap, tag: "feDisplacementMap"
	register_element :feDistantLight, tag: "feDistantLight"
	register_element :feDropShadow, tag: "feDropShadow"
	register_element :feFlood, tag: "feFlood"
	register_element :feFuncA, tag: "feFuncA"
	register_element :feFuncB, tag: "feFuncB"
	register_element :feFuncG, tag: "feFuncG"
	register_element :feFuncR, tag: "feFuncR"
	register_element :feGaussianBlur, tag: "feGaussianBlur"
	register_element :feImage, tag: "feImage"
	register_element :feMerge, tag: "feMerge"
	register_element :feMergeNode, tag: "feMergeNode"
	register_element :feMorphology, tag: "feMorphology"
	register_element :feOffset, tag: "feOffset"
	register_element :fePointLight, tag: "fePointLight"
	register_element :feSpecularLighting, tag: "feSpecularLighting"
	register_element :feSpotLight, tag: "feSpotLight"
	register_element :feTile, tag: "feTile"
	register_element :feTurbulence, tag: "feTurbulence"
	register_element :filter, tag: "filter"
	register_element :foreignObject, tag: "foreignObject"
	register_element :g, tag: "g"
	register_element :image, tag: "image"
	register_element :line, tag: "line"
	register_element :linearGradient, tag: "linearGradient"
	register_element :marker, tag: "marker"
	register_element :mask, tag: "mask"
	register_element :metadata, tag: "metadata"
	register_element :mpath, tag: "mpath"
	register_element :path, tag: "path"
	register_element :pattern, tag: "pattern"
	register_element :polygon, tag: "polygon"
	register_element :polyline, tag: "polyline"
	register_element :radialGradient, tag: "radialGradient"
	register_element :rect, tag: "rect"
	register_element :script, tag: "script"
	register_element :set, tag: "set"
	register_element :stop, tag: "stop"
	register_element :style, tag: "style"
	register_element :svg, tag: "svg"
	register_element :switch, tag: "switch"
	register_element :symbol, tag: "symbol"
	register_element :text, tag: "text"
	register_element :textPath, tag: "textPath"
	register_element :title, tag: "title"
	register_element :tspan, tag: "tspan"
	register_element :use, tag: "use"
	register_element :view, tag: "view"
end
