# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "phlex", path: "../phlex", require: ["phlex", "phlex/markdown"]
gem "phlex-rails", path: "../phlex-rails"

gem "capybara"
gem "rails"
gem "syntax_suggest"
gem "zeitwerk"

gem "filewatcher"
gem "htmlbeautifier"
gem "redcarpet"
gem "markly"
gem "webrick"
gem "rouge"
